import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Insta Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello Universe!</h1>

      {/* Header */}
      {/* Feed */}
      {/* Modal */}
    </div>
  );
}
